name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - java: 17
          - java: 25
    steps:
    - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: actions/checkout@v7
    - uses: coursier/cache-action@v8
    - uses: sbt/setup-sbt@v1
    - run: sbt
           -v
           --server
           "all scalafmtSbtCheck scalafmtCheckAll"
           testFull
      shell: bash
